### ISSUE TITLE
Review of assessment

### ISSUE THREAD

**Issue by sputten** [Nicolaas0411/huffman-encoding#1]
The code works but needed some hacking as the Readme is not accurate:

1. The instructions to build the container: `docker build . -t huffman-encoding` were missing
2. The docker-compose.yml entry for huffman-service should be: 
````
huffman-service:
    image: huffman-encoding:latest
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    links:
      - rabbitmq
````
3. The instructions in the readme should contain how to exec into the pod
4. Instructions to start the nameco service should have been: `nameko shell --config config.yml` 
5. The last instruction in the Readme is incorrect, it should have been: `n.rpc.engineering_assessment.decodeEncodedString(encodedString="1000111110000011011110110")`
